# Generated by Django 6.1.1 on 2026-09-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_change_price', 'Может менять цену книги')]},
        ),
    ]
